# Generated by Django 3.2.12 on 2023-04-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_auto_20230418_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='energy',
        ),
    ]
