# Generated by Django 3.2.12 on 2023-04-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_remove_item_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=25),
        ),
    ]
