# Generated by Django 3.2.12 on 2023-04-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0004_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=82),
        ),
    ]
