# Generated by Django 3.2.12 on 2023-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0005_auto_20230420_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=87),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
