# Generated by Django 3.2.12 on 2023-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0011_auto_20230420_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=73),
        ),
    ]
