# Generated by Django 3.2.12 on 2023-04-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0013_auto_20230421_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=22),
        ),
    ]
