# Generated by Django 3.2.12 on 2023-04-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0014_auto_20230421_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=93),
        ),
    ]
