# Generated by Django 3.2.12 on 2023-04-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0015_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=85),
        ),
        migrations.CreateModel(
            name='ICA_Luthagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(verbose_name='Expiry date')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.item')),
            ],
        ),
    ]
