# Generated by Django 3.2.12 on 2023-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0017_auto_20230426_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ica_luthagen',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=89),
        ),
    ]
