# Generated by Django 3.2.12 on 2023-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0018_auto_20230426_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ica_luthagen',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='ica_luthagen',
            name='id',
        ),
        migrations.AlterField(
            model_name='ica_luthagen',
            name='expiry_date',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=59),
        ),
    ]
