# Generated by Django 3.2.12 on 2023-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0019_auto_20230426_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='ica_luthagen',
            name='pantry_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=61),
        ),
    ]
