# Generated by Django 3.2.12 on 2023-04-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0020_auto_20230427_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement_amount',
            fields=[
                ('amount_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement_unit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measurement_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
        migrations.CreateModel(
            name='Recipe_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.item')),
                ('measurement_amount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.measurement_amount')),
                ('measurement_unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.measurement_unit')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.recipe')),
            ],
        ),
    ]
