# Generated by Django 3.2.12 on 2023-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0021_auto_20230428_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='ica_luthagen',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
