# Generated by Django 3.2.12 on 2023-05-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0022_auto_20230502_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
