# Generated by Django 3.2.12 on 2023-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0023_remove_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
