# Generated by Django 3.2.12 on 2023-05-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0024_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ica_luthagen',
            name='expiry_date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='Expiry date'),
        ),
    ]
