# Generated by Django 3.2.12 on 2023-05-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0026_auto_20230503_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ica_luthagen',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
