# Generated by Django 3.2.12 on 2023-05-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0027_auto_20230503_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ica_luthagen',
            name='pantry_product',
        ),
        migrations.AddField(
            model_name='item',
            name='pantry_product',
            field=models.BooleanField(default=False),
        ),
    ]
