# Generated by Django 3.2.12 on 2023-05-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0028_auto_20230503_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ica_luthagen',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='ica_luthagen',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Item.item'),
        ),
    ]
