# Generated by Django 3.2.12 on 2023-05-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0029_auto_20230503_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_ingredients',
            old_name='amount',
            new_name='measurement_amount',
        ),
    ]
