# Generated by Django 3.2.12 on 2023-05-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0030_rename_amount_recipe_ingredients_measurement_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_ingredients',
            name='key_ingredient',
            field=models.BooleanField(default=False),
        ),
    ]
