# Generated by Django 3.2.12 on 2023-05-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0031_recipe_ingredients_key_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(default='', null=True),
        ),
    ]
