# Generated by Django 3.2.12 on 2023-05-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0032_auto_20230507_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(default='', null=True),
        ),
    ]
