# Generated by Django 3.2.12 on 2023-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0033_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe_ingredients',
            name='ingredient_amount',
            field=models.IntegerField(default=0),
        ),
    ]
